# DPS TCK sample configuration


# Configure the test package, typically you would test control-plane and data-plane separately
# so append ".controlplane" or ".dataplane" respectively.
dataspacetck.test.package=org.eclipse.dataspacetck.dps.verification

# URL the TCK will POST signaling messages to on the control-plane under test
tck.dps.controlplane.webhook.url=http://localhost:9191/api/v1/dataflows

# URL of the DSP protocol endpoint used by the TCK to drive negotiations
tck.dps.controlplane.protocol.url=http://localhost:8282/api/v1/dsp

# URL of the data-plane under test
tck.dps.dataplane.url=http://localhost:8585/api/v1/dataflows

# Authorization token sent in requests to the data-plane (defaults to "dummy-authorization")
tck.dps.dataplane.authorization=dummy-authorization

# Maximum time (seconds) the TCK waits for an async response
tck.dps.default.wait=15
