/*
 *  Copyright (c) 2026 Think-it GmbH
 *
 *  This program and the accompanying materials are made available under the
 *  terms of the Apache License, Version 2.0 which is available at
 *  https://www.apache.org/licenses/LICENSE-2.0
 *
 *  SPDX-License-Identifier: Apache-2.0
 *
 *  Contributors:
 *       Think-it GmbH - initial API and implementation
 *
 */

package org.eclipse.dataspacetck.dps.system.client;

/**
 * Client for signaling the control plane under test to trigger data flow operations.
 */
public interface ControlPlaneClient {

    /**
     * Sends a signal to the control plane to trigger a data flow preparation.
     * The control plane generates the process ID and returns it in the {@code id} field of the response body.
     *
     * @param agreementId  the contract agreement ID
     * @param datasetId    the dataset ID
     * @param dataPlaneUrl the URL of the data plane (TCK) that will receive the DataFlowPrepareMessage
     * @return the process ID generated by the control plane
     */
    String triggerDataFlowPreparation(String agreementId, String datasetId, String dataPlaneUrl);

    /**
     * Sends a signal to the control plane to trigger a data flow preparation, but does NOT send the DSP
     * TransferRequestMessage. The DSP TransferRequestMessage will only be sent after the control plane
     * receives the async PREPARED callback (see {@link #notifyPrepared}).
     * The control plane generates the process ID and returns it in the {@code id} field of the response body.
     *
     * @param agreementId  the contract agreement ID
     * @param datasetId    the dataset ID
     * @param dataPlaneUrl the URL of the data plane (TCK) that will receive the DataFlowPrepareMessage
     * @return the process ID generated by the control plane
     */
    String triggerDataFlowPreparationAsync(String agreementId, String datasetId, String dataPlaneUrl);

    /**
     * Sends the async PREPARED callback to the control plane, notifying it that the data flow has reached the PREPARED state.
     *
     * @param processId       the transfer process ID
     * @param dataFlowId      the data flow ID assigned by the data plane
     */
    void notifyPrepared(String processId, String dataFlowId);

    /**
     * Sends the async STARTED callback to the control plane, notifying it that the data flow has reached the STARTED state.
     *
     * @param processId       the transfer process ID
     * @param dataFlowId      the data flow ID assigned by the data plane
     */
    void notifyStarted(String processId, String dataFlowId);

}
